using System.Text.Json;
using Allure.Net.Commons.Attributes;
using green_city_sh.Tests.Api.Clients;
using green_city_sh.Tests.Api.Clients.GreencityUser;
using green_city_sh.Tests.Api.DTO;
using green_city_sh.Tests.Api.DTO.EcoNewsComment;
using green_city_sh.Tests.Infrastructure;
using RestSharp;

namespace green_city_sh.Tests.Tests.API;

[TestFixture]
[Parallelizable(ParallelScope.Fixtures)]
[AllureOwner("Petro Derlytsia")]
[AllureSubSuite("Eco News Comment API")]
public class EcoNewsCommentApiTests
{
    private OwnSecurityClient _client;
    private EcoNewsCommentClient _ecoNewsCommentClient;
    private const string ImagePath = "TestData/test_image.jpg";
    private long _testNewsId = 10420;

    private long _setupCommentId;
    private long _createdCommentId;

    [OneTimeSetUp]
    public void OneTimeSetUp()
    {
        _client = new OwnSecurityClient(Configuration.ApiUserBaseUrl);
        SignInModal signInModel = new SignInModal
        {
            email = Configuration.TestEmail,
            password = Configuration.TestPassword
        };
        RestResponse response = _client.SignIn(signInModel);

        Assert.That(response.StatusCode, Is.EqualTo(System.Net.HttpStatusCode.OK));
        Assert.That(response.Content, Is.Not.Null.And.Not.Empty);

        var authResponse = JsonSerializer.Deserialize<AuthResponce>(response.Content);

        Assert.That(authResponse, Is.Not.Null);
        Assert.That(authResponse.accessToken, Is.Not.Null.And.Not.Empty);

        _ecoNewsCommentClient = new EcoNewsCommentClient(Configuration.ApiGreenCityBaseUrl, authResponse.accessToken);
    }

    [SetUp]
    public void SetUp()
    {
        var requestDto = new AddCommentRequest
        {
            text = "Pre-condition comment generated by automation"
        };

        RestResponse response = _ecoNewsCommentClient.AddComment(_testNewsId, requestDto);
        var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
        var createdComment = JsonSerializer.Deserialize<EcoNewsCommentResponse>(response.Content, options);

        _setupCommentId = createdComment.Id;
    }

    [TearDown]
    public void TearDown()
    {
        if (_setupCommentId != 0)
        {
            _ecoNewsCommentClient.DeleteComment(_setupCommentId);
            _setupCommentId = 0;
        }

        if (_createdCommentId != 0)
        {
            _ecoNewsCommentClient.DeleteComment(_createdCommentId);
            _createdCommentId = 0;
        }
    }

    [Test]
    [AllureDescription("Verify adding eco news comment successfully")]
    [AllureSubSuite("Eco-news-comment-controller")]
    [AllureTag("API", "Smoke")]
    public void VerifyAddingEcoNewsCommentSuccessfully()
    {
        var expectedText = "Test comment generated by automation";

        var requestDto = new AddCommentRequest
        {
            text = expectedText
        };

        RestResponse response = _ecoNewsCommentClient.AddComment(_testNewsId, requestDto);

        Assert.That(response.StatusCode, Is.EqualTo(System.Net.HttpStatusCode.Created));

        var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
        var createdComment = JsonSerializer.Deserialize<EcoNewsCommentResponse>(response.Content, options);

        Assert.That(createdComment, Is.Not.Null);

        _createdCommentId = createdComment.Id;

        Assert.Multiple(() =>
        {
            Assert.That(createdComment.Text, Is.EqualTo(expectedText));
            Assert.That(createdComment.Author.Id, Is.EqualTo(Configuration.TestUserId));
        });
    }

    [Test]
    [AllureDescription("Verify getting eco news comment by ID")]
    [AllureSubSuite("Eco-news-comment-controller")]
    [AllureTag("API", "Smoke")]
    public void VerifyGettingEcoNewsCommentById()
    {
        RestResponse response = _ecoNewsCommentClient.GetCommentById(_setupCommentId);

        Assert.That(response.StatusCode, Is.EqualTo(System.Net.HttpStatusCode.OK));

        var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
        var retrievedComment = JsonSerializer.Deserialize<EcoNewsCommentResponse>(response.Content, options);

        Assert.That(retrievedComment, Is.Not.Null);

        Assert.Multiple(() =>
        {
            Assert.That(retrievedComment.Id, Is.EqualTo(_setupCommentId));
            Assert.That(retrievedComment.Text, Is.EqualTo("Pre-condition comment generated by automation"));
            Assert.That(retrievedComment.Author.Id, Is.EqualTo(Configuration.TestUserId));
        });
    }

    [Test]
    [AllureDescription("Verify updating eco news comment")]
    [AllureSubSuite("Eco-news-comment-controller")]
    [AllureTag("API", "Smoke")]
    public void VerifyUpdatingEcoNewsComment()
    {
        var updatedText = "Updated test comment generated by automation";

        RestResponse response = _ecoNewsCommentClient.UpdateComment(_setupCommentId, updatedText);

        Assert.That(response.StatusCode, Is.EqualTo(System.Net.HttpStatusCode.OK));

        RestResponse getResponse = _ecoNewsCommentClient.GetCommentById(_setupCommentId);

        var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
        var retrievedComment = JsonSerializer.Deserialize<EcoNewsCommentResponse>(getResponse.Content, options);

        Assert.That(retrievedComment.Text, Is.EqualTo(updatedText));
    }

    [Test]
    [AllureDescription("Verify deleting eco news comment")]
    [AllureSubSuite("Eco-news-comment-controller")]
    [AllureTag("API", "Smoke")]
    public void VerifyDeletingEcoNewsComment()
    {
        RestResponse deleteResponse = _ecoNewsCommentClient.DeleteComment(_setupCommentId);
        Assert.That(deleteResponse.StatusCode, Is.EqualTo(System.Net.HttpStatusCode.OK));

        RestResponse getResponse = _ecoNewsCommentClient.GetCommentById(_setupCommentId);
        Assert.That(getResponse.StatusCode, Is.EqualTo(System.Net.HttpStatusCode.OK));

        var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
        var retrievedComment = JsonSerializer.Deserialize<EcoNewsCommentResponse>(getResponse.Content, options);

        Assert.That(retrievedComment.Status, Is.EqualTo("DELETED"));

        _setupCommentId = 0;
    }
}
