using System.Text.Json;
using Allure.Net.Commons.Attributes;
using green_city_sh.Tests.Api.Clients;
using green_city_sh.Tests.Api.Clients.GreencityUser;
using green_city_sh.Tests.Api.DTO;
using green_city_sh.Tests.Api.DTO.EcoNewsComment;
using green_city_sh.Tests.Infrastructure;
using RestSharp;

namespace green_city_sh.Tests.Tests.API;

[TestFixture]
[Parallelizable(ParallelScope.Fixtures)]
[AllureOwner("Petro Derlytsia")]
[AllureFeature("Eco News Comment API")]
public class EcoNewsCommentApiTests
{
    private OwnSecurityClient _client;
    private EcoNewsCommentClient _ecoNewsCommentClient;
    private const string ImagePath = "TestData/test_image.jpg";
    private long _testNewsId = 10420;
    private long _createdCommentId;


    [OneTimeSetUp]
    public void OneTimeSetUp()
    {
        _client = new OwnSecurityClient(Configuration.ApiUserBaseUrl);
        SignInModal signInModel = new SignInModal
        {
            email = Configuration.TestEmail,
            password = Configuration.TestPassword
        };
        RestResponse response = _client.SignIn(signInModel);

        Assert.That(response.StatusCode, Is.EqualTo(System.Net.HttpStatusCode.OK), "Authentication failed");
        Assert.That(response.Content, Is.Not.Null.And.Not.Empty, "Authentication response should not be empty");

        var authResponse = JsonSerializer.Deserialize<AuthResponce>(response.Content);

        Assert.That(authResponse, Is.Not.Null, "Failed to deserialize auth response");
        Assert.That(authResponse.accessToken, Is.Not.Null.And.Not.Empty, "Access token should not be empty");

        _ecoNewsCommentClient = new EcoNewsCommentClient(Configuration.ApiGreenCityBaseUrl, authResponse.accessToken);
    }

    [Test]
    [Order(1)]
    [AllureDescription("Verify adding eco news comment successfully")]
    [AllureSubSuite("Eco-news-comment-controller")]
    [AllureTag("API", "Smoke")]
    public void VerifyAddingEcoNewsCommentSuccessfully()
    {
        var expectedText = "Test comment generated by automation";
        
        var requestDto = new AddCommentRequest
        {
            Text = expectedText
        };

        RestResponse response = _ecoNewsCommentClient.AddComment(_testNewsId, requestDto);

        Assert.That(response.StatusCode, Is.EqualTo(System.Net.HttpStatusCode.Created), "Status code should be 201 Created");
        
        var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
        var createdComment = JsonSerializer.Deserialize<EcoNewsCommentResponse>(response.Content, options);

        Assert.That(createdComment, Is.Not.Null, "Failed to deserialize created comment response");
        
        _createdCommentId = createdComment.Id;

        Assert.Multiple(() =>
        {
            Assert.That(createdComment.Text, Is.EqualTo(expectedText), "Comment text does not match");
            Assert.That(createdComment.Author.Id, Is.EqualTo(Configuration.TestUserId), "Author ID does not match");
        });
    }
    [Test]
    [Order(2)]
    [AllureDescription("Verify getting eco news comment by ID")]
    [AllureSubSuite("Eco-news-comment-controller")]
    [AllureTag("API", "Smoke")]
    public void VerifyGettingEcoNewsCommentById()
    {
        RestResponse response = _ecoNewsCommentClient.GetCommentById(_createdCommentId);

        Assert.That(response.StatusCode, Is.EqualTo(System.Net.HttpStatusCode.OK), "Status code should be 200 OK");

        var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
        var retrievedComment = JsonSerializer.Deserialize<EcoNewsCommentResponse>(response.Content, options);

        Assert.That(retrievedComment, Is.Not.Null, "Failed to deserialize retrieved comment response");

        Assert.Multiple(() =>
        {
            Assert.That(retrievedComment.Id, Is.EqualTo(_createdCommentId), "Retrieved comment ID does not match");
            Assert.That(retrievedComment.Text, Is.EqualTo("Test comment generated by automation"), "Retrieved comment text does not match");
            Assert.That(retrievedComment.Author.Id, Is.EqualTo(Configuration.TestUserId), "Author ID does not match");
        });
    }

    [Test]
    [Order(3)]
    [AllureDescription("Verify updating eco news comment")]
    [AllureSubSuite("Eco-news-comment-controller")]
    [AllureTag("API", "Smoke")]
    public void VerifyUpdatingEcoNewsComment()
    {
        var updatedText = "Updated test comment generated by automation";

        RestResponse response = _ecoNewsCommentClient.UpdateComment(_createdCommentId, updatedText);

        Assert.That(response.StatusCode, Is.EqualTo(System.Net.HttpStatusCode.OK), "Status code should be 200 OK");

        RestResponse getResponse = _ecoNewsCommentClient.GetCommentById(_createdCommentId);
        
        var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
        var retrievedComment = JsonSerializer.Deserialize<EcoNewsCommentResponse>(getResponse.Content, options);

        Assert.That(retrievedComment.Text, Is.EqualTo(updatedText), "Comment text was not updated successfully");
    }

    [Test]
    [Order(4)]
    [AllureDescription("Verify deleting eco news comment")]
    [AllureSubSuite("Eco-news-comment-controller")]
    [AllureTag("API", "Smoke")]
    public void VerifyDeletingEcoNewsComment()
    {
        RestResponse deleteResponse = _ecoNewsCommentClient.DeleteComment(_createdCommentId);
        Assert.That(deleteResponse.StatusCode, Is.EqualTo(System.Net.HttpStatusCode.OK), "Status code should be 200 OK after deletion call");

        RestResponse getResponse = _ecoNewsCommentClient.GetCommentById(_createdCommentId);
        Assert.That(getResponse.StatusCode, Is.EqualTo(System.Net.HttpStatusCode.OK), "Comment still exists in DB, so GET should return 200 OK");

        var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
        var retrievedComment = JsonSerializer.Deserialize<EcoNewsCommentResponse>(getResponse.Content, options);

        Assert.That(retrievedComment.Status, Is.EqualTo("DELETED"), "Comment status was not changed to DELETED");
    }
}    